### ISSUE TITLE
Python 3.10 error - exampels/gcr_example.py - AttributeError: module 'collections' has no attribute 'Mapping'

### ISSUE THREAD

**Issue by dgahle** [johnson-c/ColRadPy#7]
`collections.Mapping` does not work in python 3.9 or 3.10. Please updated README.txt to say that Python 3.8 is required to run ColRadPy

AttributeError: 
  File "C:\Users\dsgah\github\ColRadPy\colradpy\colradpy_class.py", line 305, in update_dict
    if isinstance(v, collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'

More info on the error: https://stackoverflow.com/questions/70195545/module-collections-has-no-attribute-mapping-issue-on-macos-for-sdk-installa

**Comment by johnson-c** [comment]
Thanks Daljeet, I'll look into this today to tomorrow. I think probably get around using "collections".

**Comment by d-v-t** [comment]
Hi all,
It seems the fix is quite simple. In python3.10, collections.Mapping moved to collections.abc.Mapping. @johnson-c you already stated that you wanted to move away from collections but if not, this should work. I added in a try-except statement at the beginning to use either the <3.10 or >=3.10 syntax.

[colradpy_class.zip](https://github.com/johnson-c/ColRadPy/files/11337633/colradpy_class.zip)

**Comment by johnson-c** [comment]
Thanks d-v-t, I've updated to check versioning.
